# This is a config file with the general options for DEBUG
# a comment

#----------------------------------------------------------------------------------------------------------------
# Experiment set
finetune_mode: true
pretrained_model_dir: "./logging/resnet-conformer_mse_bi_level:True_k_ops:5_kops_linear:True_n_proj_layer:1_5.0_sf:4000.0__2024-06-23-16:54:36"
optimizer: 'Adam'




bi_nums : 0

threshold: 40

#sampling: 'prob'
temperature: 2.0
stage_num: 1  # 阶段数



weight_decay: 1.e-6
#scheduler: 'WarmupLR'
#scheduler_conf: {
## 学习率预热步数，对应的是step/accum_grad
#"warmup_steps": 8000, # 每个epoch 有 45个batch 前20个epoch 预热训练
# # 最小学习率
#"min_lr": 1e-6}
#num_epochs: 100
#each_epoch_nums_iters: 2000



#----------------------------------------------------------------------------------------------------------------
# SELD SET
#f_pool_size: [8,4]
#dropout_rate: 0.05         # Dropout rate, constant for all layers
#nb_cnn2d_filt: 64
#rnn_size: 128
#nb_fnn_layers: 1
#nb_heads: 8,
#nb_self_attn_layers: 2
#nb_rnn_layers: 2
#fnn_size: 128

#----------------------------------------------------------------------------------------------------------------
# Experiment metadata
exp_name: train
exp_group: ''
seed_mode: balanced     # ['balanced', 'random']
seed: 5678
mode: train             # ['train', 'valid', 'eval']
debug: false
profiling: false
logging_dir: './logging'
wandb: false
oracle_mode: false

#----------------------------------------------------------------------------------------------------------------
# Training
num_iters: 200000

num_workers: 0
print_every: 200
logging_interval: 2000
solver: vanilla  # ['DAN', 'vanilla']
disc_algorithm: vanilla

# Predictor
G_crit: ls
lr: 1e-4
lr_scheduler_step: 4000
lr_min: 1e-7
lr_decay_rate: 0.90
lr_patience_times: 3
w_rec: 100
w_adv: 0
G_rec_spec: l1
w_rec_spec: 0.0

# Discriminator
D_crit: ls # choices=['minmax', 'non-sat', 'ls', 'wass', 'hinge']
D_lr: 1e-1
D_lr_min: 1e-7
D_lr_decay_rate: 0.9
D_lr_patience_times: 3
D_lr_weight_decay: 0.001
D_lr_scheduler: lrstep
D_lr_scheduler_step: 1000
D_lr_scheduler_T_0: 5000
D_lr_scheduler_T_mult: 1
D_batches: 0
D_grad_clip: 10
curriculum_D_threshold_min: 0.0
curriculum_D_threshold_max: 0.0
curriculum_w_adv: 0.0

# Scheduler
curriculum_scheduler: linear


#----------------------------------------------------------------------------------------------------------------
# Models

# Predictor


model_normalization: batchnorm
detection_threshold: 0.5
thresh_unify: 15
use_mixup: false
mixup_alpha: 0.2


# Discriminator
disc: DiscriminatorModularThreshold
disc_input_shape:  [3, 256, 256]      # These are labels, or upsampled labels, or conditioned-upsampled labels
disc_feature_maps: 64
disc_final: none
disc_kernels: ["4,4", "4,4", "4,4", "4,4", "2,2"]
disc_strides: ["2,2", "2,2", "4,4", "4,4", "2,2"]
disc_padding: [1, 1, 1, 1, 0]
disc_normalization: instance
disc_block: coord
disc_conditioning: none-upsample
disc_final_multi: 4
disc_threshold_min: 0.3
disc_threshold_max: 1.5
disc_use_spectral_norm: true
disc_use_threshold_norm: true
disc_use_threshold_binarize: false
disc_use_low_pass: false
disc_with_r: false
disc_freq_pooling: none


#----------------------------------------------------------------------------------------------------------------
# Dataset

dataset_chunk_mode: random        # ['random', 'fixed', 'full']

dataset_ignore_pad_labels: false
dataset_trim_wavs: -1

dataset_root: ['/home/yupeng/datasets/dcase2023']
dataset_list_train: ['dcase2023_devtrain_all.txt']

#dataset_root: ['/home/yupeng/datasets/dcase2023','/home/yupeng/datasets/DCASE2022_SELD_synth_data']
#dataset_list_train: ['dcase2023_devtrain_all.txt','synth_data_devtrain_all.txt']

#dataset_list_train: ['yu_train.txt']

dataset_root_valid: '/home/yupeng/datasets/dcase2023'
dataset_list_valid: 'dcase2023_devtest_all.txt'




#---------------------------------------------------------------------------------------------------------------
# 常用设置
bi_level: false      # ada-network-seld strategy
fix: true          # fix strategy
k_ops: 5            # operation nums
kops_linear: false  # use random kops
search_freq : 4000   # 可以做实验来探讨
n_proj_layer: 0      # 可以做实验来探讨
split: 0.2            # no use
dataset_multi_track: false
dataset_backend: sony        # ['sony', 'baseline']
model: crnn10      # ['baseline','crnn10', 'resnet-conformer','samplecnn', 'samplecnn_gru']
model_features_transform: stft_iv     # ['mel_iv_base','stft_iv', 'mel_iv', 'mel_base', 'none']
#dataset_chunk_size_seconds: 5.11  # For example 1.27, or 2.55 or 5.11
model_loss_fn: mse     # ['mse', 'bce','adpit']
use_aug : true  #是否使用数据增强

model_spatialmixup: true
model_augmentation: true
model_spec_augmentation: false
model_rotations: false
model_rotations_mode: azi
model_rotations_noise: false
#seld
#batch_size: 18
#input_shape: [7, 251 , 64 ]      # 'input_shape': [4, 144000], when using sample cnn
#output_shape: [50, 117] #3*3*13
#dataset_chunk_size_seconds: 5
#t_pool_size: [1,1,1]

#crnn10
batch_size: 10
input_shape: [7, 256, 256]      # 'input_shape': [4, 144000], when using sample cnn
output_shape: [3, 12, 256]
dataset_chunk_size_seconds: 5.11  # For example 1.27, or 2.55 or 5.11

#resnet-conformer
#batch_size: 10
#input_shape: [10,7,500,64]
#output_shape: [50, 117]
#dataset_chunk_size_seconds: 5  # For example 1.27, or 2.55 or 5.11
#----------------------------------------------------------------------------------------------------------------
# Evaluation
evaluation_overlap_fraction: 1
